import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Footer from "../components/Footer";
import ImageIntro from "../components/ImageIntro";
import Button from "../components/ui/Button";
import Introduction from "../components/ui/Introduction";
import ServiceCard from "../components/ui/Servicecard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-bgnoise bg-blurblack pb-24 mb-24 px-6">
          <h1 className="text-white font-MontHeavy text-5xl leading-large mb-6">
            Results focused design & development agency.
          </h1>
          <p className="text-lightgray leading-small text-lg mb-8 font-sans ">
            Extend your team with our high performing specialists or hire us to
            shape your product from scratch. Either way, we’ll get your product
            off the ground and build a momentum for your success.
          </p>
        </div>
        <div>
          <ImageIntro url="/Mockup_1.png" variant="green" />
          <ImageIntro url="/Fiona_Thumbnail.png" variant="purple" />
          <ImageIntro url="/thumbnail.png" variant="orange" />
        </div>
        <div className="bg-black bg-opacity-90 bg-bgnoise pt-24 px-6 pb-24">
          <h2 className="text-white font-MontBold text-medium leading-large pb-8">
            Our services
          </h2>
          <div className="grid gap-16 ">
            <ServiceCard variant="product" />
            <ServiceCard variant="dev" />
            <ServiceCard variant="quality" />
            <ServiceCard variant="marketing" />
            <Button title={"see Our Services"} />
          </div>
        </div>
        {/* another section */}
        <div className="pt-24 px-6 grid gap-8 bg-[#F6F6F6] pb-24">
          <h2 className="text-medium font-MontBold leading-normal mb-8 text-lightblack">
            Agile team on demand
          </h2>
          <div className="w-[261px]">
            <img src="/people.png" alt="people" />
          </div>
          <div>
            <p className="text-gray32 text-smallx leading-middle">
              By hiring and managing talented people with skills specific to
              your project, we build you a team that’s accomplished, agile and
              scalable in both directions.
            </p>
          </div>
          <Button title="See How It Works" />
        </div>
        {/* another section */}
        <div className="pt-14  relative px-6 pb-24 ">
          <div className="font-MontBold text-extralarge absolute -top-7 -left-1 text-bluegradient">
            “
          </div>
          <h1 className="text-lightblack font-MontBold text-mediumx leading-medium">
            They are consistent, and the communication is good.
          </h1>
          <div className="min-h-[182px] mb-8 items-center  mt-8 justify-center flex">
            <p className="text-smallx text-[#525252] leading-middle ">
              When I have a deadline, they would work extra hours on the weekend
              and after hours. Cinnamon gives the impression of being a smaller
              team that’s focused on customers.
            </p>
          </div>

          <div className=" flex flex-col flex-wrap items-start text-lightblack gap-1">
            <div className="rounded-full w-16 h-16 overflow-hidden">
              <img src="/pp.png" alt="profile" />
            </div>
            <h5 className="text-small font-MontBold leading-small">
              Garin Toren,
            </h5>
            <p className="text-smallx font-sans leading-middle">CEO, ping</p>
          </div>
          <div>
            <div className="grid ">
              {/* arrows */}
              <div className="flex justify-between w-[168px] mt-12">
                <button className="cursor-pointer">
                  <div>
                    <img src="left.png" alt="arrow" />
                  </div>
                </button>
                <button className="cursor-pointer">
                  <div>
                    <img src="right.png" alt="arrow" />
                  </div>
                </button>
              </div>
              {/* view case */}
              <div className=" flex gap-3 items-center mt-8">
                <div>
                  <img src="arrowright.svg" alt="arrowright" />
                </div>
                <Link href="/#">
                  {" "}
                  <p className="uppercase font-MontBold text-smallx leading-middle text-[#5135FF] underline underline-offset-2 ">
                    VIEW CASE STUDY
                  </p>
                </Link>
              </div>
            </div>
          </div>
        </div>
        {/* another section */}
        <div className="pt-24 bg-[#F6F6F6] pb-24">
          <div className="px-6 mx-auto">
            <Introduction title='Who we are' subtitle='Meet our international teams made up of 86 innovators, branched into 8 departments, that influence the market throughout 20 different countries.'/>
            <div className="w-72 mb-6 mt-8"><img src="man.png" alt="man"/></div>
            <Button title='Read About Us'/>
    
          </div>

        </div>
        {/* College section */}
        <div className="pt-24 pb-24">
          <div className="px-6">
            <div className="w-72"><img src="/college.png" alt="college"/></div>
            <div className="min-h-[182px] items-center  mt-8 justify-center flex">
            <p className="text-smallx text-[#525252] leading-middle ">
            Seize the unique opportunity to participate in a wide range of courses conducted by professionals with an impeccable reputation in the digital industry.
            </p>
          </div>
          <Button title='See How it works'/>

          </div>

        </div>
        {/* growing section */}
        <div className="bg-black bg-opacity-90 bg-bgnoise pt-24 px-6 pb-24">
          <h1 className="font-MontBold text-4xl  leading-medium text-white mb-4">We’re growing</h1>
          <p className="font-sans text-lg leading-middle text-[#CFCFCF] mb-4">Jump on board with Cinnamon and get the privilege of working on challenging projects for leading global companies! Make the world a better, more connected place.</p>
          <Button title='See All Positions'/>
                {/* arrows */}
          <div className="pt-6">
            {/* arrow 1 */}
          <div className="flex justify-between items-center border-b  border-gray-600 ">
            <p className="text-white font-semibold text-2xl py-6 pr-3 pl-1  font-MontBold">Android Developer</p>
            <div className="w-12"><img src="/arrowwhite.webp"/></div>
          </div>
          {/* arrow 2 */}
          <div className="flex justify-between items-center border-b  border-gray-600">
            <p className="text-white font-semibold text-2xl py-6 pr-3 pl-1  font-MontBold">Android Developer</p>
            <div className="w-12"><img src="/arrowwhite.webp"/></div>
          </div>
          {/* arrow 3 */}
          <div className="flex justify-between items-center border-b  border-gray-600">
            <p className="text-white font-semibold text-2xl py-6 pr-3 pl-1  font-MontBold">Backend Development Team Lead"</p>
            <div className="w-12"><img src="/arrowwhite.webp"/></div>
          </div>
        </div>
       
        </div>
        {/* offices */}
        <div>

        </div>

  {/* last section */}
        <div className="bg-[#F6F6F6] relative">
          <div className="absolute bottom-0 left-0 w-[120px]"><img src="/colors.png"/></div>
        
        <div>
          <div className="px-6 mx-auto max-w-[1120px]">
            <div className="py-24 flex flex-col items-center text-center relative gap-5">
              <h2 className="font-MontBold leading-[56px] text-4xl ">Let's Work Together</h2>
              <Button title='Contact Us'/>

            </div>

          </div>
        </div>
        </div>
        
      </main>
      <Footer/>
    </>
  );
}
